version: 2.1

executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/node
    environment:
      TZ: /usr/share/zoneinfo/Asia/Tokyo

commands:
  attach:
    steps:
      - attach_workspace:
          at: .
  persist:
    steps:
      - persist_to_workspace:
          root: .
          paths:
            - "*"
  ssh_keys:
    steps:
      - add_ssh_keys:
          fingerprints:
            - "d8:61:dc:05:cf:02:8b:3a:65:80:42:69:f6:2f:e9:96"
      - run:
          command: ssh-keyscan github.com >> ~/.ssh/known_hosts

jobs:
  setup:
    executor: default
    steps:
      - run:
          name: System information
          command: |
            echo "Node $(node -v)"
            echo "Yarn v$(yarn -v)"
      - checkout
      - restore_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Setup
          command: |
            yarn setup
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist
  build:
    executor: default
    steps:
      - attach
      - run:
          name: Build
          command: |
            yarn build
      - store_artifacts:
          path: dist
      - persist
  deploy:
    executor: default
    parameters:
      stage:
        type: enum
        enum: [ "none", "dev" ]
    steps:
      - attach
      - ssh_keys
      - deploy:
          command: |
            yarn deploy -u "`git --no-pager show -s --format='%cn <%ce>' HEAD`" `[ "<< parameters.stage >>" = "none" ] && echo " -n"`


workflows:
  build-deploy-flow:
    jobs:
      - setup
      - build:
          requires:
            - setup
      - deploy:
          stage: none
          requires:
            - build
          filters:
            branches:
              ignore: source
      - deploy:
          stage: dev
          requires:
            - build
          filters:
            branches:
              only: source
